title: "Afsan Sarwer"
logo: "/assets/img/headshot.jpg"
description: "**Prospective PhD student**"
show_downloads: false
google_analytics:  # Add your Google Analytics ID if needed
theme: jekyll-theme-minimal
show_footer: false  # Disable the "Hosted on GitHub Pages" footer
